.TH "src/DetectionMain.cpp" 3 "Mon Dec 9 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DetectionMain.cpp \- main file for Detection node  

.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <ros/service_client\&.h>\fP
.br
\fC#include '\&.\&./include/Detection\&.hpp'\fP
.br
\fC#include '\&.\&./include/IDetection\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
main file for Detection node 


.PP
\fBAuthor:\fP
.RS 4
Kartik Madhira 
.PP
Arjun Gupta 
.PP
Aruna Baijal 
.RE
.PP
\fBCopyright:\fP
.RS 4
MIT License (c) 2019 Kartik Madhira, Aruna Baijal, Arjun Gupta 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
