.TH "src/main.cpp" 3 "Mon Dec 9 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/UserInterface\&.hpp'\fP
.br
\fC#include '\&.\&./include/WarehouseManager\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
