.TH "src/Navigation.cpp" 3 "Mon Dec 9 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Navigation.cpp \- Navigation class Implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Navigation\&.hpp'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef actionlib::SimpleActionClient< move_base_msgs::MoveBaseAction > \fBMoveBaseClient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Navigation class Implementation\&. 


.PP
\fBAuthor:\fP
.RS 4
Kartik Madhira 
.PP
Arjun Gupta 
.PP
Aruna Baijal 
.RE
.PP
\fBCopyright:\fP
.RS 4
MIT License (c) 2019 Kartik Madhira, Aruna Baijal, Arjun Gupta 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef actionlib::SimpleActionClient<move_base_msgs::MoveBaseAction> \fBMoveBaseClient\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
