.TH "src/UserInterface.cpp" 3 "Mon Dec 9 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/UserInterface.cpp \- Implements UserInterface class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'UserInterface\&.hpp'\fP
.br
\fC#include 'WarehouseManager\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Implements UserInterface class\&. 


.PP
\fBAuthor:\fP
.RS 4
Kartik Madhira 
.PP
Arjun Gupta 
.PP
Aruna Baijal 
.RE
.PP
\fBCopyright:\fP
.RS 4
MIT License (c) 2019 Kartik Madhira, Aruna Baijal, Arjun Gupta 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
