.TH "src/WarehouseManager.cpp" 3 "Mon Dec 9 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/WarehouseManager.cpp \- Implements WarehouseManager class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'WarehouseManager\&.hpp'\fP
.br
\fC#include <exception>\fP
.br
\fC#include <string>\fP
.br

.SH "Detailed Description"
.PP 
Implements WarehouseManager class\&. 


.PP
\fBAuthor:\fP
.RS 4
Kartik Madhira 
.PP
Arjun Gupta 
.PP
Aruna Baijal 
.RE
.PP
\fBCopyright:\fP
.RS 4
MIT License (c) 2019 Kartik Madhira, Aruna Baijal, Arjun Gupta 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
